import Head from 'next/head'
import Image from 'next/image'
import Navbar from './common/Navbar'
import Sidebar from './common/Sidebar'
import Body from './homeComponents/Body'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Monodome - Dashboard</title>
        <meta name="description" content="Generated by Monodome" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <Navbar />
        <div className="container-fluid p-lg-5">
          <div className="row flex-nowrap">
            <Sidebar />
            <Body />
          </div>
        </div>
      </main>
    </div>
  )
}
